"""Add api_message_id to sms_logs table

Revision ID: 040a3e812155
Revises: 3c4579f15f6e
Create Date: 2025-09-16 04:18:52.196804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040a3e812155'
down_revision: Union[str, None] = '3c4579f15f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_logs', sa.Column('api_message_id', sa.String(length=50), nullable=True))
    op.drop_index(op.f('idx_students_grade_class'), table_name='students')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_students_grade_class'), 'students', ['grade', 'class_letter'], unique=False)
    op.drop_column('sms_logs', 'api_message_id')
    # ### end Alembic commands ###
