"""Add class_letter to students table and composite index

Revision ID: 3c4579f15f6e
Revises: e99e8833fc28
Create Date: 2025-09-15 07:53:57.790565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4579f15f6e'
down_revision: Union[str, None] = 'e99e8833fc28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('class_letter', sa.String(length=1), nullable=False, server_default='A'))
    op.create_unique_constraint('uq_student_name_grade_class', 'students', ['name', 'grade', 'class_letter'])
    op.create_check_constraint('check_class_letter', 'students', "class_letter ~ '^[A-Z]$'")
    op.create_index('idx_students_grade_class', 'students', ['grade', 'class_letter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_students_grade_class', table_name='students')
    op.drop_constraint('check_class_letter', 'students', type_='check')
    op.drop_constraint('uq_student_name_grade_class', 'students', type_='unique')
    op.drop_column('students', 'class_letter')
    # ### end Alembic commands ###
